remote_theme: JS-DevTools/gh-pages-theme

title: Ono
logo: https://jsdevtools.org/img/logos/logo.png

author:
  twitter: JSDevTools

google_analytics: UA-68102273-3

twitter:
  username: JSDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://jsdevtools.org/img/logos/card.png
  - scope:
      path: "test/specs/**/*"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
